# Generated by Django 4.0.3 on 2022-03-19 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +996[код][номер]', regex='^(\\+996)\\d{9}$')])),
                ('number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(choices=[('1y', '1y'), ('2y', '2y'), ('3y', '3y'), ('4y', '4y'), ('5y', '5y'), ('6y', '6y'), ('7y', '7y'), ('8y', '8y'), ('9y', '9y'), ('10y', '10y')], max_length=3)),
            ],
        ),
    ]
