# Generated by Django 4.0.3 on 2022-03-19 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +996[код][номер]', regex='^(\\+996)\\d{9}$')]),
        ),
    ]
